DOCS_DIR = "resources/docs/"
USERS_DIR = "resources/users/"
PASSWORD_FILE = "password.txt"
HISTORY_DIR = "history/"
META_DIR = "meta/"
META_FILE = "meta.json"

AI_UPLOAD = "http://localhost:8080/uploadfiles"
AI_ANSWER = "http://localhost:8080/answer"
AI_FIRST_MESSAGE = "Ты — умный ассистент."